### PR TITLE
User Status Dashboard

### PR DESCRIPTION
**Pull request by anjali-sharma**
This dashboard can be temporarily used to set **send_warning_email_after** flag. Shall later add the other elements to the dashboard as per the new UI design.

### CODE REVIEW

**Comment by alma-castant** [comment]
@anjali-sharma is this following the mockup on MyBalsamiq? It has not been approved yet and we should not be using that approach. We should instead put this functionality on the user profile when organizers see it

**Comment by anjali-sharma** [comment]
@alma-castant Ohk sure. I'll change it as per the new mockup.

**Comment by anjali-sharma** [comment]
@DMips I have updated the PR as per the new mockup. Apologies for the delay. :)

**Comment by DMips** [comment]
@anjali-sharma sorry for the delay ;)

**Pull request merged**
